"""Interactive configuration wizard for PDF Summarizer."""

from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from pdf_summarizer import __version__
from pdf_summarizer.config import config

console = Console()


def show_config_check(
    setup: bool = typer.Option(
        False,
        "--setup",
        "-s",
        help="启动交互式配置向导",
    ),
):
    """检查配置状态或启动配置向导。"""
    if setup:
        _run_config_wizard()
        return

    settings = config.settings

    table = Table(title="API 配置状态")
    table.add_column("提供商", style="cyan")
    table.add_column("API Key", style="green")
    table.add_column("模型", style="blue")
    table.add_column("状态", style="yellow")

    providers = [
        ("OpenAI", settings.openai_api_key, settings.openai_model),
        ("Claude", settings.anthropic_api_key, settings.anthropic_model),
        ("Kimi", settings.kimi_api_key, settings.kimi_model),
    ]

    for name, key, model in providers:
        status = "[green]✓ 已配置[/]" if key else "[red]✗ 未配置[/]"
        key_display = f"{key[:8]}..." if key and len(key) > 8 else key or "N/A"
        table.add_row(name, key_display, model, status)

    console.print(table)

    try:
        from pdf_summarizer.ai_client import get_provider_stats

        stats = get_provider_stats()

        cache_stats = stats.get('cache', {})
        console.print(f"\n[bold]缓存状态[/]")
        console.print(f"  目录: {cache_stats.get('cache_dir', 'N/A')}")
        console.print(f"  条目数: {cache_stats.get('total_entries', 0)}")
        console.print(f"  大小: {cache_stats.get('total_size_mb', 0)} MB")

    except Exception as e:
        console.print(f"\n[yellow]无法获取缓存状态: {e}[/]")

    console.print(f"\n默认提供商: [bold]{settings.default_provider}[/]")
    console.print(f"输出目录: [bold]{settings.output_directory}[/]")
    console.print(f"\n[dim]提示: 使用 --setup 参数启动配置向导[/]")


def _run_config_wizard():
    """交互式配置向导。"""
    console.print("\n[bold cyan]═══ PDF Summarizer 配置向导 ═══[/]\n")

    env_path = Path(".env")
    env_example = Path(".env.example")

    if not env_path.exists() and env_example.exists():
        console.print("[yellow]未找到 .env 文件，将从模板创建...[/]")
        import shutil

        shutil.copy(env_example, env_path)
        console.print("[green]✓ 已创建 .env 文件[/]\n")

    console.print("[bold]请选择默认 AI 提供商：[/]")
    console.print("  1. OpenAI (GPT-4o)")
    console.print("  2. Claude (Anthropic)")
    console.print("  3. Kimi (Moonshot)")

    provider_choice = typer.prompt(
        "请输入选项 (1-3)",
        default="3",
        show_default=True,
    )

    provider_map = {"1": "openai", "2": "claude", "3": "kimi"}
    provider = provider_map.get(provider_choice, "kimi")

    console.print(f"\n[bold]配置 {provider.upper()} API Key：[/]")

    api_key = typer.prompt(
        f"请输入 {provider.upper()} API Key",
        default="",
        show_default=False,
        hide_input=True,
    )

    if not api_key:
        console.print("[red]错误：API Key 不能为空[/]")
        raise typer.Exit(1)

    console.print(f"\n[bold]选择模型：[/]")
    if provider == "openai":
        console.print("  1. gpt-4o (推荐)")
        console.print("  2. gpt-4o-mini")
        console.print("  3. gpt-4-turbo")
        model_choice = typer.prompt("请输入选项", default="1")
        model_map = {"1": "gpt-4o", "2": "gpt-4o-mini", "3": "gpt-4-turbo"}
    elif provider == "claude":
        console.print("  1. claude-sonnet-4-6-20250514 (推荐)")
        console.print("  2. claude-opus-4-7")
        model_choice = typer.prompt("请输入选项", default="1")
        model_map = {"1": "claude-sonnet-4-6-20250514", "2": "claude-opus-4-7"}
    else:
        console.print("  1. moonshot-v1-8k")
        console.print("  2. moonshot-v1-32k (推荐)")
        console.print("  3. moonshot-v1-128k")
        model_choice = typer.prompt("请输入选项", default="2")
        model_map = {"1": "moonshot-v1-8k", "2": "moonshot-v1-32k", "3": "moonshot-v1-128k"}

    model = model_map.get(model_choice, list(model_map.values())[0])

    output_dir = typer.prompt(
        "\n输出目录",
        default="./output",
    )

    env_content = f"""# AI API Keys Configuration
# Generated by PDF Summarizer Config Wizard

# Default Provider
DEFAULT_PROVIDER={provider}

# OpenAI Configuration
OPENAI_API_KEY={"sk-" + api_key[3:] if provider == "openai" else ""}
OPENAI_MODEL=gpt-4o

# Anthropic Configuration
ANTHROPIC_API_KEY={"sk-ant-" + api_key[7:] if provider == "claude" else ""}
ANTHROPIC_MODEL=claude-sonnet-4-6-20250514

# Kimi Configuration
KIMI_API_KEY={api_key if provider == "kimi" else ""}
KIMI_MODEL={model}

# Output Settings
OUTPUT_DIRECTORY={output_dir}

# Cache Settings
CACHE_ENABLED=true
CACHE_MAX_AGE_HOURS=24
"""

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    console.print(f"\n[green]✓ 配置已保存到 {env_path}[/]")
    console.print(f"\n[bold]配置摘要：[/]")
    console.print(f"  提供商: [cyan]{provider}[/]")
    console.print(f"  模型: [cyan]{model}[/]")
    console.print(f"  输出目录: [cyan]{output_dir}[/]")
    console.print(f"\n[bold]下一步：[/]")
    console.print(f"  pdf-summarizer process your_file.pdf --provider {provider}")
